"""Display labels and table metadata for the PyQt dashboard."""

TABLE_CONFIG = {
    "Analysis": ("analysis_results", "analyzed_at"),
    "Events": ("event_logs", "detected_at"),
    "GPT Calls": ("gpt_call_logs", "started_at"),
    "Signals": ("signal_logs", "detected_at"),
    "Paper Results": ("paper_trade_results", "evaluated_at"),
    "Notifications": ("notification_logs", "sent_at"),
    "Historical Bars": ("historical_bars", "bar_time"),
    "Context Snapshots": ("market_context_snapshots", "collected_at"),
}

TAB_LABELS = {
    "Analysis": "분석결과",
    "Events": "이벤트",
    "GPT Calls": "GPT 호출",
    "Signals": "신호",
    "Paper Results": "모의검증",
    "Notifications": "알림",
    "Historical Bars": "과거봉",
    "Context Snapshots": "컨텍스트",
}

TABLE_NAME_LABELS = {
    "ticks": "틱 데이터",
    "analysis_results": "분석 결과",
    "event_logs": "이벤트 로그",
    "gpt_call_logs": "GPT 호출 로그",
    "signal_logs": "신호 로그",
    "notification_logs": "알림 로그",
    "historical_bars": "과거 봉 데이터",
    "market_context_snapshots": "시장 컨텍스트",
}

COLUMN_LABELS = {
    "action_hint": "판단",
    "analyzed_at": "분석시각",
    "asof": "기준시각",
    "bar_time": "봉시각",
    "box_high": "박스상단",
    "box_low": "박스하단",
    "box_position": "박스위치",
    "change_rate": "등락률",
    "code": "종목코드",
    "collected_at": "수집시각",
    "completion_tokens": "응답토큰",
    "confidence_score": "신뢰점수",
    "codes": "요청종목",
    "current_price": "현재가",
    "description": "설명",
    "detected_at": "감지시각",
    "duration_ms": "소요ms",
    "entry_price": "진입가",
    "entry_time": "진입시각",
    "error_message": "오류",
    "evaluated_at": "평가시각",
    "event_type": "이벤트",
    "gpt_requested": "GPT요청",
    "high": "고가",
    "id": "ID",
    "item": "항목",
    "key": "설정키",
    "latest_events": "최근이벤트",
    "latest_signal": "최근신호",
    "low": "저가",
    "ma5": "5이평",
    "ma20": "20이평",
    "ma60": "60이평",
    "market_context_json": "시장컨텍스트JSON",
    "max_gain_30m_pct": "30분최대수익률",
    "max_gain_60m_pct": "60분최대수익률",
    "max_loss_30m_pct": "30분최대손실률",
    "max_loss_60m_pct": "60분최대손실률",
    "message": "메시지",
    "model": "모델",
    "name": "종목명",
    "open": "시가",
    "outcome_label": "결과",
    "payload_compressed_chars": "압축후문자수",
    "payload_compression_ratio": "압축률",
    "payload_json": "Payload JSON",
    "payload_original_chars": "압축전문자수",
    "payload_preview": "Payload 미리보기",
    "price": "가격",
    "prompt_chars": "프롬프트문자수",
    "prompt_tokens": "입력토큰",
    "reason_json": "근거JSON",
    "received_at": "수신시각",
    "reliability": "신뢰도",
    "requested_count": "요청종목수",
    "result_json": "결과JSON",
    "result_preview": "결과미리보기",
    "return_5m_pct": "5분수익률",
    "return_10m_pct": "10분수익률",
    "return_30m_pct": "30분수익률",
    "return_60m_pct": "60분수익률",
    "risk_level": "위험도",
    "rsi14": "RSI14",
    "scope": "범위",
    "section": "구분",
    "sent_at": "발송시각",
    "signal_id": "신호ID",
    "skip_reason": "제외사유",
    "source": "출처",
    "started_at": "시작시각",
    "status": "상태",
    "stop_loss": "손절가",
    "strength": "체결강도",
    "summary": "요약",
    "summary_json": "요약JSON",
    "target_1": "목표1",
    "target_1_hit": "목표1도달",
    "target_2": "목표2",
    "target_2_hit": "목표2도달",
    "timeframe": "주기",
    "total_tokens": "총토큰",
    "trade_time": "체결시각",
    "trading_value": "거래대금",
    "updated_at": "수정시각",
    "value": "값",
    "value_type": "값형식",
    "volume": "거래량",
    "volume_ratio_5": "5봉거래량배율",
    "volume_ratio_20": "20봉거래량배율",
    "vwap": "VWAP",
    "vwap_distance_pct": "VWAP이격률",
    "weight": "가중치",
}

VALUE_LABELS_BY_COLUMN = {
    "action_hint": {
        "AVOID_CHASE": "추격주의",
        "AVOID_MARKET_RISK": "시장위험 회피",
        "AVOID_SUPPLY": "매도압력 주의",
        "OBSERVE_EVENT": "이벤트 관찰",
        "WATCH_BREAKOUT": "돌파 관찰",
        "WATCH_MOMENTUM": "모멘텀 관찰",
        "WATCH_PULLBACK": "눌림목 관찰",
        "WATCH_REBOUND": "반등 관찰",
        "WATCH_RESISTANCE": "저항 관찰",
        "WATCH_SUPPORT": "지지 관찰",
    },
    "event_type": {
        "CONSECUTIVE_DOWN_BARS": "연속 하락봉",
        "CONSECUTIVE_UP_BARS": "연속 상승봉",
        "MA5_MA20_DEAD_CROSS": "5/20 데드크로스",
        "MA5_MA20_GOLDEN_CROSS": "5/20 골든크로스",
        "MARKET_CIRCUIT_BREAKER_ACTIVE": "서킷브레이커",
        "MARKET_SIDECAR_ACTIVE": "사이드카",
        "MARKET_VI_ACTIVE": "VI 상태",
        "MARKET_FOREIGN_SELL_PRESSURE": "시장 외국인 매도 압력",
        "NEAR_BOX_HIGH": "박스 상단 근접",
        "NEAR_BOX_LOW": "박스 하단 근접",
        "NEAR_VWAP_RESISTANCE": "VWAP 저항 근접",
        "NEAR_VWAP_SUPPORT": "VWAP 지지 근접",
        "ORDERBOOK_ASK_IMBALANCE": "매도호가 우세",
        "ORDERBOOK_BID_IMBALANCE": "매수호가 우세",
        "RSI_OVERBOUGHT": "RSI 과열",
        "RSI_OVERSOLD": "RSI 침체",
        "VOLUME_SPIKE": "거래량 급증",
    },
    "gpt_requested": {
        "0": "미요청",
        "1": "요청",
    },
    "outcome_label": {
        "no_level_hit_60m": "60분 내 목표/손절 미도달",
        "not_evaluated": "미평가",
        "stop_before_target": "목표 전 손절",
        "target_1_before_stop": "목표1 우선 도달",
        "target_1_hit": "목표1 도달",
        "target_2_before_stop": "목표2 우선 도달",
    },
    "risk_level": {
        "low": "낮음",
        "medium": "보통",
        "high": "높음",
    },
    "scope": {
        "global": "전체",
        "code": "종목",
    },
    "section": {
        "credit": "신용매매",
        "derivatives": "파생/PCR",
        "disclosures": "공시",
        "investor_flow": "투자자 수급",
        "market_indices": "시장지수",
        "market_program_trading": "프로그램매매",
        "market_status": "시장상태",
        "news": "뉴스",
        "orderbook": "호가",
        "public_reaction": "대중반응",
        "short_selling": "공매도",
    },
    "status": {
        "failed": "실패",
        "simulated": "시뮬레이션",
        "skipped": "건너뜀",
        "success": "성공",
    },
    "stop_loss_hit": {
        "0": "아니오",
        "1": "예",
    },
    "target_1_hit": {
        "0": "아니오",
        "1": "예",
    },
    "target_2_hit": {
        "0": "아니오",
        "1": "예",
    },
}

SETTING_DESCRIPTIONS_KO = {
    "ENABLE_EVENT_FILTER": "True이면 이벤트가 감지될 때만 GPT를 호출합니다.",
    "ENABLE_GPT_INPUT_COMPRESSION": "원본 DB 근거는 유지하면서 GPT 입력 payload를 압축합니다.",
    "ENABLE_KIWOOM_TR_CONTEXT_REQUESTS": "검증된 키움 TR 컨텍스트 갱신을 사용합니다.",
    "ENABLE_NOTIFICATIONS": "알림 전송 기능을 사용합니다.",
    "ENABLE_PAPER_TRADE_EVALUATION": "충분한 미래 틱이 쌓이면 저장된 검증 신호를 평가합니다.",
    "EVENT_BOX_HIGH_POSITION": "박스권 상단 근접 판단 기준입니다.",
    "EVENT_BOX_LOW_POSITION": "박스권 하단 근접 판단 기준입니다.",
    "EVENT_CONSECUTIVE_BARS": "연속 상승/하락 봉 이벤트 판단 기준 개수입니다.",
    "EVENT_ORDERBOOK_IMBALANCE": "매수/매도 호가 불균형 이벤트 판단 기준입니다.",
    "EVENT_RSI_HIGH": "RSI 과열 판단 기준입니다.",
    "EVENT_RSI_LOW": "RSI 침체 판단 기준입니다.",
    "EVENT_VOLUME_RATIO": "거래량 급증 판단 기준입니다.",
    "EVENT_VWAP_NEAR_PCT": "VWAP 근접 판단 기준 퍼센트입니다.",
    "GPT_ANALYSIS_INTERVAL_SEC": "분석 루프 주기입니다. 다음 사이클부터 적용됩니다.",
    "GPT_COOLDOWN_SEC": "같은 종목에 대해 GPT를 다시 호출하기 전 최소 대기 시간입니다.",
    "GPT_INPUT_MAX_ACTION_STATS": "GPT 입력에 포함할 액션 통계 최대 개수입니다.",
    "GPT_INPUT_MAX_CONTEXT_ITEMS": "뉴스/공시/반응 섹션별 GPT 입력 최대 항목 수입니다.",
    "GPT_INPUT_MAX_RECENT_SIGNALS": "GPT 입력에 포함할 최근 신호 최대 개수입니다.",
    "GPT_INPUT_MAX_TEXT_CHARS": "자연어 컨텍스트 필드별 최대 문자 수입니다.",
    "GPT_INPUT_RECENT_POINTS": "GPT 입력에 유지할 주기별 최근 가격/거래량 포인트 수입니다.",
    "GPT_MAX_TOKENS": "GPT 최대 출력 토큰입니다. import 시점 설정이므로 재시작이 필요합니다.",
    "MARKET_CONTEXT_TR_MAX_REQUESTS_PER_BATCH": "컨텍스트 갱신 1회당 예약할 최대 TR 요청 수입니다.",
    "MARKET_CONTEXT_TR_REQUEST_DELAY_MS": "키움 시장 컨텍스트 TR 요청 간 지연 시간입니다.",
    "MARKET_CONTEXT_TR_REQUEST_INTERVAL_SEC": "느린 TR 컨텍스트 갱신 주기입니다.",
    "MIN_TICKS_FOR_ANALYSIS": "분석 시작 전 필요한 최소 메모리 틱 개수입니다.",
    "NOTIFICATION_CHANNELS": "알림 채널입니다. 예: [\"console\", \"telegram\"]",
    "NOTIFICATION_COOLDOWN_SEC": "같은 종목 알림을 다시 보내기 전 최소 대기 시간입니다.",
    "NOTIFICATION_MAX_EVENTS": "한 알림 메시지에 포함할 최대 이벤트 개수입니다.",
    "PAPER_TRADE_EVALUATION_LIMIT": "분석 사이클당 평가할 대기 검증 신호 최대 개수입니다.",
    "PRELOAD_RECENT_TICKS_FROM_DB": "main.py 시작 시 최근 저장 틱을 메모리에 불러옵니다.",
    "PRELOAD_TICKS_MAX_AGE_MINUTES": "이 시간보다 최신인 틱만 시작 시 불러옵니다.",
    "PRELOAD_TICKS_PER_CODE": "시작 시 종목별로 불러올 최근 틱 최대 개수입니다.",
    "TELEGRAM_MAX_MESSAGE_CHARS": "로컬에서 자를 텔레그램 메시지 최대 길이입니다.",
    "TELEGRAM_TIMEOUT_SEC": "텔레그램 sendMessage 요청 HTTP 타임아웃입니다.",
    "TRADE_BUY_FEE_PCT": "GPT 비용 반영 분석에 사용할 예상 매수 수수료율입니다.",
    "TRADE_SELL_FEE_PCT": "GPT 비용 반영 분석에 사용할 예상 매도 수수료율입니다.",
    "TRADE_SELL_TAX_PCT": "GPT 비용 반영 분석에 사용할 예상 매도 거래세율입니다.",
    "TRADE_SLIPPAGE_PCT": "GPT 비용 반영 분석에 사용할 예상 편도 슬리피지입니다.",
    "WATCH_CODES": "관심 종목 맵입니다. main.py 다음 분석 사이클에서 재등록됩니다.",
    "MARKET_BENCHMARK_CODES": "시장 컨텍스트 ETF 맵입니다. 틱은 저장하지만 종목별 GPT 분석과 TR 요청에서는 제외합니다.",
    "ENABLE_MARKET_FLOW_DIRECTION_RISK": "시장 외국인 매도, 프로그램 순매도, ETF 약세가 겹칠 때 방향성 위험 이벤트를 활성화합니다.",
    "EVENT_MARKET_FLOW_REQUIRE_WEAK_ETF_COUNT": "시장 수급 위험 이벤트에 필요한 약세 ETF 최소 개수입니다.",
    "SIGNAL_MARKET_FLOW_RISK_PENALTY": "시장 수급 위험 이벤트 발생 시 검증 신호 점수 감점입니다.",
}


